<a href="https://colab.research.google.com/github/PacktPublishing/Hands-On-Computer-Vision-with-PyTorch/blob/master/Chapter02/Initializing_a_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
x = torch.tensor([[1,2]])
y = torch.tensor([[1],[2]])

In [2]:
print(x.shape)
# torch.Size([1,2]) # one entity of two items
print(y.shape)
# torch.Size([2,1]) # two entities of one item each
print(x.dtype)
# torch.int64

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


In [3]:
x = torch.tensor([False, 1, 2.0])
print(x)
# tensor([0., 1., 2.])

tensor([0., 1., 2.])


In [4]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
torch.randint(low=0, high=10, size=(3,4)) #between 0 and 9 inclusive

tensor([[5, 4, 5, 1],
        [2, 8, 4, 5],
        [7, 1, 5, 0]])

In [7]:
torch.rand(3, 4) #between 0 and 1

tensor([[0.5535, 0.9427, 0.2033, 0.6998],
        [0.2868, 0.4584, 0.7803, 0.9050],
        [0.0849, 0.4952, 0.6096, 0.4630]])

In [8]:
torch.randn((3,4))

tensor([[ 0.8061, -1.4856,  0.4589, -1.9467],
        [ 1.0189,  0.2565, -0.8790,  0.1659],
        [ 2.3324,  0.7216, -0.2283, -1.8147]])

In [9]:
#numpy array to torch tensor
import numpy as np
x = np.array([[10,20,30],[2,3,4]])
y = torch.tensor(x)
print(type(x), type(y))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
